version: '3'
services:
  backend:
    build: .
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/dbname
    depends_on:
      - database
    networks:
      - mynetwork

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PostgreSQL
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
